version: "3.1"
services:
  nginx:
    build:
      context:  ./service/nginx
      args:
        NGINX_VERSION: ${NGINX_VERSION}
    ports:
      - "454:443"
      - "8090:80"
    volumes:
      - ./www:/var/nginx/www
      - ./service/nginx/conf.d:/etc/nginx/conf.d
    container_name: 'dockernginx'


