###php
version: '2'
services:
  nginx:
    image: nginx:latest
    ports:
      - "8060:80"

    volumes_from:
      - app
    container_name:  php-nginx-mee

  app:
    build:
      context: ./
      dockerfile: php.dockerfile
    volumes:
      - ./:/var/www
      - ./nginx/conf:/etc/nginx/conf.d
      - ./php:/usr/local/etc/php/conf.d
    container_name: phpd

  mydb:
    build:
      context: ./
      dockerfile: ./mysql/dockerfile
    environment:
    - "MYSQL_DATABASE=homestead"
    - "MYSQL_USER=homestead"
    - "MYSQL_PASSWORD=secret"
    - "MYSQL_ROOT_PASSWORD=secret"
    volumes:
      - ./mysql:/var/lib/mysql
    ports:
     - "33066:3306"
    container_name: mydb

